# Generated by Django 3.2.6 on 2021-08-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='full_url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='hashed_url',
            new_name='hashed',
        ),
    ]
